services:
  c3i-backup-one-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: c3i-backup-one
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    environment:
      - NODE_ENV=development
    ports:
      - "4096:4096"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/c3i-backup-one:/var/lib/c3i-backup-one
      - ./app:/app/app
      - ~/.config/rclone:/root/.config/rclone

  c3i-backup-one-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - APP_VERSION=0.20.0
    container_name: c3i-backup-one
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/c3i-backup-one:/var/lib/c3i-backup-one
      - ~/.config/rclone:/root/.config/rclone

  c3i-backup-one-e2e:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: c3i-backup-one
    restart: unless-stopped
    environment:
      - DISABLE_RATE_LIMITING=true
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./playwright/data:/var/lib/c3i-backup-one/data
      - ./playwright/temp:/test-data
